### ISSUE TITLE
Appium support for ubuntu

### ISSUE THREAD

**Issue by rakshitajain5** [Genium-Framework/Appium-Support#5]
Can you please add appium support for ubuntu.

Code needs to be modified as : OS.isFamilyUnix()
 and appium.js file is located in the folder - /home/user/.linuxbrew/bin

Please let me know in case any more details are required.

**Comment by Hassan-Radi** [comment]
Hello,
Thanks for your feature request :smile: 

I am going to add this feature to the next release bucket and hopefully it would be released within a few days along with the latest changes to the code.

Please don't hesitate to request any features in the future.

Best regards,
Hassan.

**Comment by Hassan-Radi** [comment]
@rakshitajain5 
What is the node executable directory??

**Comment by starkipraggy** [comment]
If you install nodejs via the apt package manager, it should be /usr/bin/nodejs.

**Comment by ghost** [comment]
That way you would install a very old version of node the best way is to download it from the nodejs download [page.](https://nodejs.org/en/download/). Once you download it and create the symbolic links you can install appium via npm. That way insted of having a 
`
node appium.js --parameter1 --parameter2
`
 you will have a command like 
`
appium --parameter1 --parameter2
`
So it would awesome to have a way to use just the word **appium** instead of the two files.
 Thanks a lot hassan for your hard work btw. We all really appreciate it.
