### ISSUE TITLE
Problem with environnement variables

### ISSUE THREAD

**Issue by jeangb** [Genium-Framework/Appium-Support#9]
Hello,
First I would like to thank you for this project ...

I'm using a mac os.

How do you manage to make it work while the environnement variables are not known in Eclipse ?
I mean when I launch a test with an appium sever manually started, ADB is known and my tests are successfully launched.
But when I start a test with appium-support ADB isn't known anymore. I had to install an eclipse [plugin](https://github.com/JorisAerts/Eclipse-Environment-Variables) to set ANDROID_HOME for Eclipse.

Sadly I encountered the same issue with IOS. My UDID device wasn't known anymore, but I don't know what environnment variable I should set for Eclipse.
How have you been through this problem ?

**Comment by Hassan-Radi** [comment]
Eclipse adds some variables to your system Path in order to make things work, which is something you are gonna have to take care of when you run the tests on your own. Google is your best friend, here are some links that might help you:
http://stackoverflow.com/questions/1672281/environment-variables-for-java-installation
http://www.androidcentral.com/installing-android-sdk-windows-mac-and-linux-tutorial

Device UDID is something different and you have to acquire it yourself: https://www.innerfence.com/howto/find-iphone-unique-device-identifier-udid

Hopefully those links would help you solve the problem. Since this question is not related to the library, I am gonna close it.

Best regards,
Hassan

**Comment by jeangb** [comment]
Hi @Hassan-Radi,
Thank you for your answer.
I think my question wasn't very clear.
I'm perfectly able to run tests on android and ios on real devices when I start my appium servers manually.
But when I run my tests with the appium server programmatically started, eclipse isn't able to access to my environnment variables, so that's why he doesn't know what adb was. 
So I managed to get rid of the ANDROID_HOME issue, but I guess if I have this UDID issue is because Eclipse doesn't have access to some environnment variables.

I'm suprised that I am the only one having this issue.

**Comment by jeangb** [comment]
Hi @Hassan-Radi I solved my issue by setting the PATH variable in this environnement variables Eclipse plugin. FYI I had the same issue that https://github.com/appium/java-client/issues/252.
As you're using a CommandLine object to start the server, this one doesn't know the environnement variables.
Maybe this project should be upgraded to propose to set this variables or automatically detect them ?
